import { heroui } from "@heroui/react";

// Theme customization for NextUI is described in
// https://nextui.org/docs/customization/create-theme
// Find theme colors using https://colors.eva.design/
// and https://nextui-themegen.netlify.app/#

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./website/**/*.{js,ts,jsx,tsx}",
        "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                title: "Righteous, sans-serif",
            },
            fontSize: {
                title: "2.5rem",
            },
            letterSpacing: {
                title: "0.2em",
            },
        },
    },
    plugins: [
        heroui({
            themes: {
                light: {
                    colors: {
                        default: {
                            50: "#faf8f7",
                            100: "#f2eeeb",
                            200: "#ebe4df",
                            300: "#e4dbd3",
                            400: "#dcd1c8",
                            500: "#d5c7bc",
                            600: "#b0a49b",
                            700: "#8a817a",
                            800: "#655f59",
                            900: "#403c38",
                            foreground: "#000",
                            DEFAULT: "#d5c7bc",
                        },
                        primary: {
                            50: "#fdf3e3",
                            100: "#fae2bd",
                            200: "#f7d096",
                            300: "#f4bf6f",
                            400: "#f1ae49",
                            500: "#ee9d22",
                            600: "#c4821c",
                            700: "#9b6616",
                            800: "#714b10",
                            900: "#472f0a",
                            foreground: "#000",
                            DEFAULT: "#ee9d22",
                        },
                        secondary: {
                            50: "#f1e8f6",
                            100: "#dcc9e9",
                            200: "#c8a9dc",
                            300: "#b489d0",
                            400: "#9f6ac3",
                            500: "#8b4ab6",
                            600: "#733d96",
                            700: "#5a3076",
                            800: "#422356",
                            900: "#2a1637",
                            foreground: "#fff",
                            DEFAULT: "#8b4ab6",
                        },
                        success: {
                            50: "#e2fdf0",
                            100: "#bafada",
                            200: "#92f7c5",
                            300: "#6af5b0",
                            400: "#42f29a",
                            500: "#1aef85",
                            600: "#15c56e",
                            700: "#119b56",
                            800: "#0c723f",
                            900: "#084828",
                            foreground: "#000",
                            DEFAULT: "#1aef85",
                        },
                        warning: {
                            50: "#eae9fe",
                            100: "#ccc9fc",
                            200: "#aeaafa",
                            300: "#908af8",
                            400: "#726bf6",
                            500: "#544bf4",
                            600: "#453ec9",
                            700: "#37319f",
                            800: "#282474",
                            900: "#191749",
                            foreground: "#fff",
                            DEFAULT: "#544bf4",
                        },
                        danger: {
                            50: "#ffe6e6",
                            100: "#ffc3c2",
                            200: "#ffa09f",
                            300: "#ff7e7c",
                            400: "#ff5b58",
                            500: "#ff3835",
                            600: "#d22e2c",
                            700: "#a62422",
                            800: "#791b19",
                            900: "#4d1110",
                            foreground: "#000",
                            DEFAULT: "#ff3835",
                        },
                        background: "#fefefe",
                        foreground: {
                            50: "#e2e1df",
                            100: "#b9b7b3",
                            200: "#908d86",
                            300: "#67625a",
                            400: "#3e382d",
                            500: "#150e01",
                            600: "#110c01",
                            700: "#0e0901",
                            800: "#0a0700",
                            900: "#060400",
                            foreground: "#fff",
                            DEFAULT: "#150e01",
                        },
                        content1: {
                            DEFAULT: "#f5eee9",
                            foreground: "#000",
                        },
                        content2: {
                            DEFAULT: "#e8e0ca",
                            foreground: "#000",
                        },
                        content3: {
                            DEFAULT: "#decbb1",
                            foreground: "#000",
                        },
                        content4: {
                            DEFAULT: "#d8b997",
                            foreground: "#000",
                        },
                        focus: "#b2902b",
                        overlay: "#000000",
                        divider: "#111111",
                    },
                },
                dark: {
                    colors: {
                        default: {
                            50: "#151212",
                            100: "#231e1f",
                            200: "#322b2b",
                            300: "#403738",
                            400: "#6b6465",
                            500: "#969192",
                            600: "#c1bebe",
                            700: "#ecebeb",
                            foreground: "#fff",
                            DEFAULT: "#322b2b",
                        },
                        primary: {
                            50: "#4d330b",
                            100: "#835613",
                            200: "#b87a1a",
                            300: "#ee9d22",
                            400: "#f2b354",
                            500: "#f6c985",
                            600: "#f9dfb7",
                            700: "#fdf5e9",
                            foreground: "#000",
                            DEFAULT: "#ee9d22",
                        },
                        secondary: {
                            50: "#2d183b",
                            100: "#4c2964",
                            200: "#6c398d",
                            300: "#8b4ab6",
                            400: "#a573c6",
                            500: "#bf9bd7",
                            600: "#d9c4e7",
                            700: "#f3edf8",
                            foreground: "#fff",
                            DEFAULT: "#8b4ab6",
                        },
                        success: {
                            50: "#064b2d",
                            100: "#0b804d",
                            200: "#10b46d",
                            300: "#14e88c",
                            400: "#49eda6",
                            500: "#7ef2c0",
                            600: "#b3f8da",
                            700: "#e8fdf4",
                            foreground: "#000",
                            DEFAULT: "#10b46d",
                        },
                        warning: {
                            50: "#1b184f",
                            100: "#2e2986",
                            200: "#413abd",
                            300: "#544bf4",
                            400: "#7a74f6",
                            500: "#a19cf9",
                            600: "#c7c5fb",
                            700: "#eeedfe",
                            foreground: "#fff",
                            DEFAULT: "#413abd",
                        },
                        danger: {
                            50: "#531211",
                            100: "#8c1f1d",
                            200: "#c62b29",
                            300: "#ff3835",
                            400: "#ff6562",
                            500: "#ff9290",
                            600: "#ffbebd",
                            700: "#ffebeb",
                            foreground: "#fff",
                            DEFAULT: "#c62b29",
                        },
                        background: "#080202",
                        foreground: {
                            50: "#534b4c",
                            100: "#8c8081",
                            200: "#c6b4b5",
                            300: "#ffe8ea",
                            400: "#ffedef",
                            500: "#fff2f3",
                            600: "#fff8f8",
                            700: "#fffdfd",
                            foreground: "#000",
                            DEFAULT: "#c6b4b5",
                        },
                        content1: {
                            DEFAULT: "#1d1c16",
                            foreground: "#fff",
                        },
                        content2: {
                            DEFAULT: "#392d1d",
                            foreground: "#fff",
                        },
                        content3: {
                            DEFAULT: "#563610",
                            foreground: "#fff",
                        },
                        content4: {
                            DEFAULT: "#7d5101",
                            foreground: "#fff",
                        },
                        focus: "#b2902b",
                        overlay: "#ffffff",
                        divider: "#ffffff",
                    },
                },
            },
            layout: {
                fontSize: {
                    tiny: "0.75rem",
                    small: "0.875rem",
                    medium: "1rem",
                    large: "1.125rem",
                },
                lineHeight: {
                    tiny: "1rem",
                    small: "1.25rem",
                    medium: "1.5rem",
                    large: "1.75rem",
                },
                radius: {
                    small: "0.5rem",
                    medium: "0.75rem",
                    large: "0.875rem",
                },
                borderWidth: {
                    small: "1px",
                    medium: "2px",
                    large: "3px",
                },
                disabledOpacity: "0.5",
                dividerWeight: "1",
                hoverOpacity: "0.9",
            },
        }),
    ],
};
