# ====================================================
#                       API KEYS
#
# Create a copy of this file (api_keys_template.toml)
# and fill in the values when running the server.
#
# These keys should then be kept on the computers that
# are running the relevant services.
#
# Make sure to rename the file "api_keys.toml"
#
# ====================================================

[api_keys]
admin = "YOUR_API_KEY"

checkout = "YOUR_API_KEY"

student_storage = "YOUR_API_KEY"

printers = "YOUR_API_KEY"

gmail_email = "EMAIL"
gmail_password = "PASSWORD"