[schedule]
proficiencies = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTXfKpy0HRazczqb8Zoa7J8TQ6RvIFlhsEnfLK9J1odoRRaXIvp21yzZtntsIzjIdbazXcN9GBzcF1q/pub?gid=954325037&single=true&output=csv"
schedule = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRE5Daf9Y_ydDpyAvxickgTRJcTNpE4V-Vj0W4VxkGgXHmIwq4EtVeyeSRJDzEotfSVDK82H8aetzK5/pub?gid=0&single=true&output=csv"

[printers]
ids = [
    "FLSUN-SR-1",
    "FLSUN-SR-2",
    "FLSUN-SR-3",
    "FLSUN-SR-4",
    "PRUSA-1",
    "PRUSA-2",
]

[student_storage]
A = 16
B = 16
C = 16
D = 16
E = 4
F = 4
G = 4
H = 4

[head_stewards]
names = [
    "Ethan Vazquez",
    "Charlie Weismann",
    "Cristian Gonzalez",
    "Emma Sar",
    "Ashley Cheung",
    "Jordan Stone",
]
